[general]
name = "hashset"
version = "1.1.2"
description = "Provides the `HashSet` type."

[build]
files = ["hashset.fix"]

[build.test]
files = ["test.fix"]


[[dependencies]]
name = "hash"
version = "1.0.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hash.git" }

[[dependencies]]
name = "hashmap"
version = "1.1.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashmap.git" }
