[general]
name = "hashset"
version = "0.1.0"

[build]
files = ["hashset.fix"]

[build.test]
files = ["test.fix"]

[[dependencies]]
name = "hash"
version = "0.1.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hash.git" }